services:

    nti.log.doctrine.listener:
        class: NTI\LogBundle\EventListener\DoctrineEventListener
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.event_listener, event: kernel.exception, connection: default }

    nti.kernel.listener.kernelexception:
        class: NTI\LogBundle\EventListener\KernelExceptionListener
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    nti.logger:
        class: NTI\LogBundle\Services\Logger
        arguments: ["@service_container"]